name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 20 * * 6"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: daily share
        run: |
          git config --local user.email "1085077154@qq.com"
          git config --local user.name "gaoshanshanshan"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "Daily share"
          git push
